// <auto-generated />
namespace MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ModeladdedAppGrainOfGold : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ModeladdedAppGrainOfGold));
        
        string IMigrationMetadata.Id
        {
            get { return "201608120654570_Model added AppGrainOfGold"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
