// <auto-generated />
namespace MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changedmodelGrainOfGold : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedmodelGrainOfGold));
        
        string IMigrationMetadata.Id
        {
            get { return "201608091502506_changed model GrainOfGold"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
